name: Cache-Cleanup

on: workflow_dispatch

env:
  WORKFLOW_MARKER: my

jobs:
  cache-key:
    runs-on: ubuntu-latest
    outputs:
      key: ${{ steps.key.outputs.CACHE_KEY }}
    steps:
      - name: Get code # code checkout from repo
        uses: actions/checkout@v3
      - name: Compute Key
        id: key
        run: echo "CACHE_KEY=${{ env.WORKFLOW_MARKER}}-deps-node-modules-${{ hashFiles('**/package-lock.json') }}" >> $GITHUB_OUTPUT
      - name: Show Key
        run: |
          echo "Cache-Key: ${{ steps.key.outputs.CACHE_KEY }}"
  cleanup:
    runs-on: ubuntu-latest
    needs: cache-key
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cleanup
        run: |
          echo "Install 'gh-actions-cache' action..."
          gh extension install actions/gh-actions-cache
          ACTIVE_KEY=${{ needs.cache-key.outputs.key }}
          echo "ACTIVE_KEY: $ACTIVE_KEY"
          echo "Fetching list of cache key"
          cacheKeys=$(gh actions-cache list | cut -f 1)
          echo "cacheKeys: $cacheKeys"
          echo "Deleting caches..."
          for cacheKey in $cacheKeys
          do
            echo "Check cleanup cache for key: $cacheKey"
            if [[ $cacheKey != $ACTIVE_KEY ]]; then
              echo "Delete $cacheKey from cache..."
              gh actions-cache delete $cacheKey --confirm
              echo "'$cacheKey' deleted from cache..."
            else
              echo "Not deleted! The key: $cachKey is the active key and will be used!"
            fi
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ github.token }}
